### ISSUE TITLE
Windows directories that contain "~" cause the put app.zip to fail

### ISSUE THREAD

**Issue by sfc-gh-cconner** [Snowflake-Labs/snowcli#124]
When trying to create a procedure or function on Windows when your user directory contains "~", you get a SQL complication error.  For example:

```
User directory = c:\Users\user~1
Temp directory = c:\Users\user~1/AppData/Local/Temp
```

Then the snow function/procedure create fails on putting the app.zip with:

```
SQL compilation error:
syntax error line 1 at position 26 unexpected '~'.
parse error line 1 at position 37 near '76'.
parse error line 1 at position 43 near '84'.
parse error line 1 at position 48 near '116'.
syntax error line 1 at position 59 unexpected '/'.
syntax error line 1 at position 63 unexpected '.'.
syntax error line 1 at position 68 unexpected '@HOL_DB.HARMONIZED.deployments/orders_update_sp'.
```

The put query would look like:

```
PUT file://c/:\Users\user~1\AppData\Local\Temp\tmpasdfweg/app.zip @db.schema.some_function auto_compress=false overwrite=true
```

**Comment by sfc-gh-cconner** [comment]
Changing the PUT to the following works:

```
PUT 'file://C:\\Users\\user~1\\\\AppData\\Local\\Temp\\tmpasdsadf\\app.zip' @db.schema.some_function auto_compress=false overwrite=true
```

**Comment by sfc-gh-twhite** [comment]
Looks like we're using `os` and could extend the usage with [`os.path.expanduser()`](https://docs.python.org/3/library/os.path.html#os.path.expanduser)

https://github.com/Snowflake-Labs/snowcli/blob/83d8e52e1423c529ddc0860517784457ac0a28e3/src/snowcli/snow_connector.py#L120-L143

**Comment by sfc-gh-cconner** [comment]
Maybe?  I don't know that will work though as it's a weird windows thing where the "~" doesn't mean user home, but the "~" is in the actual directory name.  When you create a user cconner and c:\users\cconner already existed for some reason, then we get c:\users\cconner~1 , so "~" will always be in the path of the file, even if we expand.  And the Snowflake backend that processes the query doesn't like the unquoted "~".

**Comment by sfc-gh-twhite** [comment]
This is something that I've implemented in the past:

```py
import os
from urllib.parse import quote

def put_file(
    conn: snowflake.connector.SnowflakeConnection, local_file_name: str, stage_location
) -> str:
    """
    Uploads local files to the stage.

    Parameters:
    -----------
    conn: snowflake.connector.SnowflakeConnection
        A connection object representing the connection to Snowflake.
    local_file_name : str
        The path to the local files to upload. To match multiple files in the path,
        you can specify the wildcard characters ``*`` and ``?``.
    stage_location:
        The stage and prefix where you want to upload the files.

    Returns:
    --------
    str
        Message indicating the package was staged correctly.

    Raises:
    -------
    ProgrammingError
        If the file does not exist or there is a problem with the underlying connection or role.

    Example:
    --------
    >>> put_file(conn, "tests/resources/t*.csv", "@mystage/prefix1")
    'PUT tests/resources/t*.csv to @mystage/prefix1.'
    """
    uri_path = "file://" + quote(os.path.abspath(local_file_name))

    char_map = {"%2A": "*", "%3F": "?"}
    for k, v in char_map.items():
        uri_path = uri_path.replace(k, v)

    conn.cursor().execute(f"PUT {uri_path} {stage_location} AUTO_COMPRESS=FALSE;")
    return f"PUT {local_file_name} to {stage_location}."
```

**Comment by AStifora** [comment]
I am experiencing this error going through the sfguide-data-engineering-with-snowpark-python quickstart. Is there anything I can do to get this functioning? How would I use the change in PUT command suggested in the comment by sfc-gh-cconner? Is there anyway I can change the temp directory that SnowCLI uses to build the app.zip file?

**Comment by AStifora** [comment]
For any users dealing with this issue. I changed my user environment variable for TEMP and TMP to use a TEMP directory I created in the root of C:. That resolved the issue for me, until the Snowflake developers can alter the SnowCLI to work with ~ in the directory.

**Comment by sfc-gh-cconner** [comment]
Thanks @AStifora , I was wondering if that would work, but I wasn't able to test it.

**Comment by sfc-gh-jsikorski** [comment]
Fixed in https://github.com/Snowflake-Labs/snowcli/pull/386
