### ISSUE TITLE
Windows path error

### ISSUE THREAD

**Issue by sfc-gh-chrisreimer** [Snowflake-Labs/snowcli#125]
...miniconda3\envs\pysnowpark\lib\site-packages\snowcli\cli\snowpark_shared.py:84 in snowpark_create

is resolving a windows temp_dir to:
'C:\\Users\\JDECAR~1\\AppData\\Local\\Temp\\tmpd52masc9'

and then erroring out due to the presence of the tilde:
ProgrammingError: 001003 (42000): SQL compilation error: syntax error line 1 at position 26 unexpected "'~'"

**Comment by sfc-gh-cconner** [comment]
Same as:

https://github.com/Snowflake-Labs/snowcli/issues/124

**Comment by sfc-gh-turbaszek** [comment]
Closing as duplicate of https://github.com/Snowflake-Labs/snowcli/issues/124
