### ISSUE TITLE
AttributeError: module 'jinja2' has no attribute 'pass_environment'

### ISSUE THREAD

**Issue by karami-omid** [Snowflake-Labs/snowcli#176]
I'm facing this issue after install the SnowCLI with Homebrew! Just run snow --version got this error!

**AttributeError: module 'jinja2' has no attribute 'pass_environment'**

Appreciate your support!

**Comment by karami-omid** [comment]
Just update the Jinja2 package!

pip install -U Jinja2

**Comment by jeffhollan** [comment]
Thanks for commenting work around. Curious how you're install snowcli? I assume with pip? Just curious how easy it is to get into this state and somehow we can better enforce min versions

**Comment by karami-omid** [comment]
Thanks for the feedback!

I guessed that I installed it through the Homebrew. 
I figured out at the various forums that discussed updating the Jinja2 package. Some attributes are unavailable in the previous old version of  "Jinja2".
