### ISSUE TITLE
SNOW-847301: `standard_zip_dir()` tries to zip its own output directory

### ISSUE THREAD

**Issue by lewinfox** [Snowflake-Labs/snowcli#177]
Thanks for this awesome tool!

I ran into an issue today trying to create a function; `standard_zip_dir()` creates its output zip file before building the list of files to zip. This appears (for me at least) to cause it to recurse until the zip file size limit is hit.

I propose excluding `dest_zip` when zipping:

![image](https://github.com/Snowflake-Labs/snowcli/assets/25552362/8403405e-33c9-4248-ac62-9aee62e9dee3)

Happy to submit a PR if that's helpful.

**Comment by sfc-gh-jsikorski** [comment]
Hi, sorry for the delay - later in the day we will file a PR solving this, along with some refactors

**Comment by sfc-gh-jsikorski** [comment]
recreate jira
