### ISSUE TITLE
SNOW-853496: ArrowResult import warning in 1.0.0 on ARM macOS running snow command

### ISSUE THREAD

**Issue by suddenrushofsushi** [Snowflake-Labs/snowcli#219]
### Python version

3.8.17, 3.9.17, 3.11.4 (Homebrew); 3.10.11 (Python package installer)

### Platform

macOS-13.4-arm64-arm-64bit

### What happened

When running `snow --help` after a clean install in virtualenvs in any version of python listed above a warning is emitted about importing ArrowResult.

This only occurs in 1.0.0 and not with previous versions such as 0.2.9.

The resulting error appears to come from the snowflake connector (potentially something upstream in the `snowflake-connect-python-nightly` package 1.0.0 references—at best a guess on my part).

The warning is present present on Homebrew and packaged python installs; the error below was from a Homebrew 3.9 installation.

Please let me know if there's additional detail you need or other logging you require.

### Console output

```Shell
snow --help
Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: dlopen(/Users/me/Projects/snowcli-test-py39/venv/lib/python3.9/site-packages/snowflake/connector/arrow_iterator.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZN5arrow12ArrayBuilder12AppendScalarERKNS_6ScalarEx'

# program execution continues normally and prints help content
```

### How to reproduce

1. On an M1 mac, create a new virtual environment (e.g. python3.9 -m venv venv)
2. Activate the environment
3. Install the library (e.g. `pip3 install snowflake-cli-labs`)
4. Run the cli help command (e.g. `snow --help`)

(edit: wrong python version listed in summary)

**Comment by sfc-gh-jsikorski** [comment]
Hello,

thank you for detailed report of the issue. We are aware of this. Error message is generated by Snow Connector, but it should not affect execution of the commands.
