### ISSUE TITLE
SNOW-861919: Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: No module named 'snowflake.connector.arrow_iterator'

### ISSUE THREAD

**Issue by sfc-gh-anugupta** [Snowflake-Labs/snowcli#234]
### What happened

Anyone else use brew to install snowcli and get this error when running snowcli?
Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: No module named 'snowflake.connector.arrow_iterator'

Most of the commands work, but I did notice things like lookup are impacted by this error:
snow snowpark package lookup pandas
Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: No module named 'snowflake.connector.arrow_iterator'

**Comment by sfc-gh-anugupta** [comment]
@sfc-gh-turbaszek  can we look into this issue reported by Chris/Jeff ?

**Comment by sfc-gh-turbaszek** [comment]
Is this a duplicate of https://github.com/Snowflake-Labs/snowcli/issues/219 ?

**Comment by sfc-gh-turbaszek** [comment]
Closed via #246
