### ISSUE TITLE
SNOW-877653: Package create / lookup no longer displays output

### ISSUE THREAD

**Issue by sfc-gh-jhollan** [Snowflake-Labs/snowcli#271]
### What happened

Previously when running something like:
```
snow snowpark package create sktime
```

I would see the output of the pip job it's kicking off so I saw what packages were being installed. Were also some messages the CLI could send with updates. in 1.0.0 those seem to no longer show and I only get a few of the messages. I assume they may have been prints or some other write that is being suppressed by default? not sure

**Comment by sfc-gh-anugupta** [comment]
Thanks jeff for reporting . @sfc-gh-turbaszek  Can we look into ? seems its a regression issue

**Comment by sfc-gh-turbaszek** [comment]
Have you used `--verbose` flag?

**Comment by jeffhollan** [comment]
--verbose and --debug didn't work for this command. Did try. Said flag not supported or something. 

Do we have logging that is enabled by default without flag? Info logging? Some of the text output here we would want to appear by default. Either that or maybe for this flag we do --debug by default somehow

**Comment by sfc-gh-turbaszek** [comment]
@jeffhollan currently `--verbose` is a flag on main level. So you need to do `snow --verbose snowpark package create sktime`. We are working on making this flag available on every level.

**Comment by sfc-gh-cconner** [comment]
This does work:

snow --verbose snowpark package lookup pandas
2023-08-10 13:37:01 INFO Package pandas is available on the Snowflake anaconda channel.

However, that's very confusing, is there not a better way?

**Comment by sfc-gh-jsikorski** [comment]
Fixed in #325
