### ISSUE TITLE
SNOW-886496: snow snowpark registry should be snow registry

### ISSUE THREAD

**Issue by sfc-gh-jhollan** [Snowflake-Labs/snowcli#296]
### What happened

Not really a bug, but noticed in snowpark container docs we have `snow registry` as the recommended command and in 1.0.0+ we moved to `snow snowpark` with rest of stuff. I asked the containers team and they mentioned the other things in snow snowpark are right (compute pool, services, etc.), however, registry is "Snowflake Image Registry" so shouldn't be under the snowpark brand / snowpark commands.

**Comment by sfc-gh-turbaszek** [comment]
Done
