### ISSUE TITLE
SNOW-887971: Set Application property for Python connections

### ISSUE THREAD

**Issue by sfc-gh-jhollan** [Snowflake-Labs/snowcli#300]
### What happened

In a previous version of SnowCLI we would add a property to the connection called "application" - this is an identifier that allows us to see and correlate Snowflake connections from specific client apps.  Would be helpful to add this back in so we can correlate better: https://github.com/Snowflake-Labs/snowcli/blob/f65e25f55b2b1b77aefdcdae52111416fe2f4fc5/src/snowcli/snow_connector.py#L43

**Comment by sfc-gh-astus** [comment]
@sfc-gh-jhollan we still have it https://github.com/Snowflake-Labs/snowcli/blob/3d11dba63e5ca2af914437ab0d9452020b19bdae/src/snowcli/snow_connector.py#L46

**Comment by jeffhollan** [comment]
Ah thank you. Do you know what the actual string looks like? Even casing? I can try to run but was trying to find the correlated connection logs and wasn't sure of string to search for.

**Comment by sfc-gh-astus** [comment]
We build it from provided command, e.g.
for `% snow stage list` we will send `SNOWCLI.STAGE.LIST`
`% snow stage create new_stage` -> `SNOWCLI.STAGE.CREATE`
`% snow warehouse status` -> `SNOWCLI.WAREHOUSE.STATUS`
