### ISSUE TITLE
SNOW-900602: Cannot put "folder/*.py" to a stage because it's not a valid Path

### ISSUE THREAD

**Issue by sfc-gh-zblackwood** [Snowflake-Labs/snowcli#331]
### Python version

Python 3.8.12

### Platform

macOS-13.5-arm64-arm-64bit

### What happened

I should be able to put `folder/*.py` to a stage, and have it only upload all the .py files from that folder to a stage.

```bash
snow stage put "shared_modules/*.py" snow://streamlit/streamlit.sis_apps.test_app_recursive/default_checkout/shared_modules
```

This should be perfectly valid https://docs.snowflake.com/en/sql-reference/sql/put#examples, but it fails because Typer is checking to see that the path is valid.

If you put `exists=False` it works fine, and uploads all of the .py files in that folder to the stage. If you put an invalid folder, you still get a File doesn't exist message, just from SQL rather than Typer.

### Console output

```Shell
╭─ Error ───────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for 'PATH': Path 'shared_modules/*.py' does not exist.                              │
╰───────────────────────────────────────────────────────────────────────────────────────────────────╯
```
```


### How to reproduce

Try to `snow put` a path with `*` in it

**Comment by sfc-gh-pjob** [comment]
We have a discussion in the linked PR but I'd like to write here that IMO it should be considered as a new feature, not a bug. If I'm wrong we should probably state what exactly was working wrong before (other way than documented).

I'll try to provide as much support as possible in the PR but if the changes start require too much work from us, then they will probably have to wait a bit (I mean mainly Windows tests case mentioned in the discussion in the PR).
