### ISSUE TITLE
Folder or project level configuration files

### ISSUE THREAD

**Issue by sfc-gh-ejohnson** [Snowflake-Labs/snowcli#40]
Currently, in our project Git repo we have to create a folder for each sproc with an app.toml when using Snowcli. So if I have 20 sprocs, I will have to structure my Git repo to have 20 folders and then have my CI pipeline call a script to traverse the repo to run the '_snow procedure ..._' command for each.  
It would be easier if we had the functionality to have one config file at the folder level or project level.

**Comment by sfc-gh-jroes** [comment]
We do [walk up the directory tree](https://github.com/Snowflake-Labs/snowcli/blob/21ffe5b80ee027b3c09874bcaa164d343462c1c1/src/snowcli/config.py#L19-L28) to find the first app.toml. I haven't looked carefully at how it interacts with the procs features though.

**Comment by sfc-gh-jhollan** [comment]
Yeah one thing I was wondering is if we introduced a `project.toml` as well. Imagine I have a directory with a layout like:

| my-project
|. project.toml
|| src
||| myproc-1
|||. app.toml
||| myproc-2
|||. app.toml
||| streamlit
|||. app.toml

could the `project.toml` more or less point to the sub-folders included in project, maybe provide some global env config, and allow something like:

`snow deploy -f project.toml --environment dev` 

So you could "bulk" deploy a bunch of stuff
