### ISSUE TITLE
SNOW-923084: Flag collision in Snowpark Container commands

### ISSUE THREAD

**Issue by sfc-gh-jhollan** [Snowflake-Labs/snowcli#405]
### SnowCLI version

1.0.1

### Python version

3.10

### Platform

mac os M1

### What happened

When running some of the commands for `services` and `jobs` in SnowCLI, I can't use the `-c` flag as it's mapped to both container_name and environment. So I have to do the long-form version:

```
snow snowpark services logs JEFF_DB.BUILD.generate_data --container_name main --environment prod3
```

Maybe we re-map container_name to -n or something

**Comment by sfc-gh-jsikorski** [comment]
This was part of #438 - will be included in next release
