### ISSUE TITLE
SNOW-923087: Ability to save the context for a "connection" across many commands

### ISSUE THREAD

**Issue by sfc-gh-jhollan** [Snowflake-Labs/snowcli#406]
### Description

Let me know if this already exists. I think the probably right pattern here would be we allow you to set the connection / environment via an environment variable.

The actual need here is I run a bunch of commands and always have to append every command with `-c connection_name` and I would love to save myself always typing. Ideally I could do like:

```
export SNOWFLAKE_CONNECTION=my_connection
snow snowpark services list
```

and it'd use `my_connection`

**Comment by sfc-gh-jsikorski** [comment]
You should already be able to do this - env variable name is "SNOWFLAKE_OPTIONS_DEFAULT_CONNECTION". We will update the docs

**Comment by sfc-gh-turbaszek** [comment]
This is already possible
https://docs.snowflake.com/LIMITEDACCESS/snowcli/connecting/connect#how-to-change-the-default-connection-for-snowflake-cli
