### ISSUE TITLE
SNOW-923096: `--format json` only works at the base command

### ISSUE THREAD

**Issue by sfc-gh-jhollan** [Snowflake-Labs/snowcli#408]
### SnowCLI version

1.0.1

### Python version

3.10

### What happened

If I run this command it says `no option --format`

`snow snowpark services list -c prod3 --format json`

But it works as long as I put it before sub commands

`snow --format json snowpark services list -c prod3`

This isn't super intuitive. Ideally you could set --format as an option in any command

**Comment by sfc-gh-jsikorski** [comment]
Can you try updating CLI to 1.1.0 and check if the problem is still present?

**Comment by sfc-gh-jhollan** [comment]
Yep! Fixed in 1.1.0. Thanks!
