### ISSUE TITLE
Project description on pypi is empty

### ISSUE THREAD

**Issue by sfc-gh-asaini** [Snowflake-Labs/snowcli#42]
![Screen Shot 2022-11-15 at 6 12 10 PM](https://user-images.githubusercontent.com/110130910/202044495-751e35cd-fd59-475f-a469-a0837930c9a4.png)

When opening the[ pypi page](https://pypi.org/project/snowflake-cli-labs/) for Snowcli, the user is presented with an empty page.

**Comment by sfc-gh-astus** [comment]
Almost fixed, still is a problem with imgaes
