### ISSUE TITLE
SNOW-929441: Registry Token doesn't work with connection override

### ISSUE THREAD

**Issue by sfc-gh-jhollan** [Snowflake-Labs/snowcli#433]
### SnowCLI version

1.1.0

### Python version

3.10

### Platform

mac os M1

### What happened

When running

`snow snowpark registry token -c prod3` it complains "connection dev is not configured."  I tried doing `--connection` and `--environment` and got same error. On second look it looks like this command has TWO connection flags registered, so I think it's fighting or only setting one. Dunno

<img width="1279" alt="image" src="https://github.com/Snowflake-Labs/snowcli/assets/105808548/f821cc5a-a1d9-416d-828f-80cacc97e67f">

**Comment by sfc-gh-astus** [comment]
We fixed it in #426 and will be in 1.1.1
