### ISSUE TITLE
Add SnowSQL installation as a step in Snowcli installation instructions

### ISSUE THREAD

**Issue by sfc-gh-asaini** [Snowflake-Labs/snowcli#44]
In 2 recent user walkthroughs, I noticed that devs tend to gloss over the initial sections and jump straight to the [Installation](https://github.com/Snowflake-Labs/snowcli#installation) section. 

Then having installed `snowflake-cli-labs` they try to run a `$ snow ...` command but run into the error saying SnowSQL is missing. 

To prevent this from happening, I propose refactoring the Installation section into 2 steps, for e.g.

### Step 1: Install SnowSQL
* If you already have SnowSQL installed, skip to Step 2
* Steps for installing SnowSQL

#### Install with homebrew

...

**Comment by smoreface** [comment]
@sfc-gh-asaini I just tested this out and didn't run into any issues installing snowcli with pip in a virtual environment. SnowSQL doesn't seem to be a prerequisite. How did you install SnowCLI, and when did you run into the error?

I'd be delighted to help SnowCLI improve their docs accordingly :)

**Comment by sfc-gh-turbaszek** [comment]
SnowCLI no longer depends on snowsql
