### ISSUE TITLE
SNOW-930444: Show active connection details

### ISSUE THREAD

**Issue by sfc-gh-yostrinsky** [Snowflake-Labs/snowcli#446]
### Description

Kind of "Who am I".
It would be nice if `snow connection test` would present the active connection parameters (no password ofc) to make sure everything is planned.
BTW, adding that to the verbose flag is also good practice across commands.

**Comment by sfc-gh-turbaszek** [comment]
Do I correctly understand that `snow connection tests` should print information about connection in use? Something like
```
> snow connection tests
Connection details:
account: foo
user: bar

Connection status: OK
```

**Comment by sfc-gh-yostrinsky** [comment]
Exactly. Thanks!
