### ISSUE TITLE
SNOW-947055: Import Error When Trying To Run App

### ISSUE THREAD

**Issue by mashhype** [Snowflake-Labs/snowcli#487]
### SnowCLI version

1.2.0

### Python version

3.9.6

### Platform

macOS-13.5.2-arm64-arm-64bit

### What happened

I've deployed my app successfully. But when I go to run the app, comes back with a ModuleNotFoundError. In my main application python file, I import a separate python file with my functions. This file sits in the same folder as the main python file.
<img width="1209" alt="Screenshot 2023-10-19 at 4 35 03 PM" src="https://github.com/Snowflake-Labs/snowcli/assets/4706698/7c7887ab-4cd3-42a6-877f-ccf91450db79">

### Console output

```Shell
(myenv) mashsyed@mashs-mbp car-trends % snow streamlit deploy cars_app --file=Home.py -c mashsf --replace --query-warehouse MED_COMPUTE_WH --debug
Streamlit successfully deployed and available under https://app.snowflake.com/JZUYHUK/fha10802/#/streamlit-apps/ANALYTICS.CARS.CARS_APP
```

### How to reproduce

I'm not sure

**Comment by mashhype** [comment]
Adding another screenshot to show what my local environment looks like
<img width="918" alt="Screenshot 2023-10-19 at 4 38 28 PM" src="https://github.com/Snowflake-Labs/snowcli/assets/4706698/343f9089-3492-4216-a644-25f3b1224476">

**Comment by sfc-gh-anugupta** [comment]
@sfc-gh-turbaszek Can we check on it ?

**Comment by sfc-gh-turbaszek** [comment]
`car_functions.py` is not uploaded to Snowflake.  That's expected as we currently upload mian file, environment.yml and files from `pages/` directory. Additional files are not yet supported.

**Comment by sfc-gh-zblackwood** [comment]
@mashhype You can add an extra command to upload that file to the associated stage, something like
```
snow stage put car_functions.py streamlit_apps.public.streamlit/cars_app --overwrite -c mashsf
```

**Comment by mashhype** [comment]
so I tried this command but its giving me an error saying: "streamlit_apps
does not exist or not authorized."
What is the default name?

ProgrammingError: 002003 (02000): 01afc772-0403-aea6-0057-9703000f4346: SQL
compilation error:
Database 'STREAMLIT_APPS' does not exist or not authorized.
(myenv) ***@***.*** car-trends %

**Comment by mashhype** [comment]
Hi @sfc-gh-turbaszek 

I tried that and got this error:
<img width="792" alt="Screenshot 2023-10-20 at 10 57 31 AM" src="https://github.com/Snowflake-Labs/snowcli/assets/4706698/09b99711-cdee-4acd-9e83-16587d78f9ae">

**Comment by mashhype** [comment]
disregard @sfc-gh-zblackwood, its literally the path to my schema and database! Thank you for your help!


<img width="792" alt="Screenshot 2023-10-20 at 11 08 33 AM" src="https://github.com/Snowflake-Labs/snowcli/assets/4706698/023580db-4b98-4a7b-9baf-5e550adc7c14">

**Comment by mashhype** [comment]
found the path needed to upload the file
