### ISSUE TITLE
SNOW-947589: Error When Running Application "No secrets files found. Valid paths for a secrets.toml file are: /home/udf/.streamlit/secrets.toml, /.streamlit/secrets.toml"

### ISSUE THREAD

**Issue by mashhype** [Snowflake-Labs/snowcli#489]
### SnowCLI version

2.0.0-dev

### Python version

3.9.6

### Platform

macOS-13.5.2-arm64-arm-64bit

### What happened

When I try to run my app, it cannot find the secrets.toml file. Where and how do I upload the file?
<img width="792" alt="Screenshot 2023-10-20 at 11 32 50 AM" src="https://github.com/Snowflake-Labs/snowcli/assets/4706698/76029271-b91a-44a7-ac1e-b7907c20e5b5">

**Comment by mashhype** [comment]
@sfc-gh-zblackwood Any thoughts on what the command should look like to upload the secrets.toml file? I tried using the same command as you suggested for the functions file, but I still get the same error above.

**Comment by sfc-gh-turbaszek** [comment]
How does it relate to snowcli?

**Comment by sfc-gh-turbaszek** [comment]
Closing this one as an issue with Streamlit not snowcli.
