### ISSUE TITLE
Unable to download non-Anaconda packages starting with 0.1.9

### ISSUE THREAD

**Issue by sfc-gh-jhansen** [Snowflake-Labs/snowcli#51]
I was trying to follow the basic demo from the [Snow CLI Overview and Quickstart](https://www.youtube.com/watch?v=WDuBeAgbTt4) (starting at 10:18) and noticed that the part around incorporating a non-Anaconda package (pyjokes) no longer works with version 0.1.9.

I tried all the possible options for the new `--pypi-download` command line parameter (yes, no, ask) but none of them helped. Basically it doesn't seem to ever prompt with "Do you want to try to download non-Anaconda packages? [Y/n]" as of version 0.1.9.

I took a quick look at the code and the problem seems to be in the changes to the `snowpark_package()` function in `snowcli/cli/snowpark_shared.py`.

**Comment by sfc-gh-jhansen** [comment]
I tried the following commands, but none of them prompted me to download the non-Anaconda package:
- `snow function package`
- `snow function package --pypi-download='ask'`
- `snow function package --pypi-download='yes'`
- `snow function package --pypi-download='no'`

**Comment by sfc-gh-jhansen** [comment]
@jamesweakley, am I missing anything here?

**Comment by jamesweakley** [comment]
@sfc-gh-jhansen apologies, I did introduce this bug in that version. There was some parameter validation that I introduced late in the piece, clearly not well tested enough.

I've opened a PR which fixes it.

**Comment by sfc-gh-jhansen** [comment]
No worries @jamesweakley, and thanks for the quick fix!

**Comment by jamesweakley** [comment]
@sfc-gh-jhansen are you able to close this? I don't have the permissions

**Comment by sfc-gh-jhansen** [comment]
Sorry for the delay here @jamesweakley, but yes, I'll close it now.
