### ISSUE TITLE
snow streamlit create with relative path to file fails

### ISSUE THREAD

**Issue by sfc-gh-zblackwood** [Snowflake-Labs/snowcli#54]
I ran the following commands:
```sh
snow streamlit create --file folder/file.py app_name
snow streamlit deploy --file folder/file.py app_name -o
```
Which created a new stage and uploaded file.py to the new stage, but put it in the base folder of the stage, while the streamlit app expected it to be located at `/folder/file.py`

SQL query
```sql
create streamlit app_name
ROOT_LOCATION = @DB.SCHEMA.app_name_stage
MAIN_FILE = '/folder/file.py'
QUERY_WAREHOUSE = WAREHOUSE;
```

The Streamlit app never ran, and showed this error 
![image](https://user-images.githubusercontent.com/102999810/211108283-915f43fd-164f-4f91-b131-5fbaa193ad7a.png)

I then went back and uploaded (through the UI) `file.py` into a new folder `/folder/` in the stage, and it worked

It seems that, if creating a streamlit only looks at the file name when uploading it to a stage, then it should also only use at the raw file name when

**Comment by sfc-gh-jroes** [comment]
Are you using my branch (#50), by chance?

**Comment by sfc-gh-zblackwood** [comment]
Nope, just installed the latest one from brew

**Comment by sfc-gh-jhollan** [comment]
Just merged to main and pushed out release. `v0.1.11` hopefully has what you need

**Comment by sfc-gh-jroes** [comment]
I don't think it will. I misremembered the contents of #50.

I honestly had never used `streamlit create` when specifying a file. Pretty sure this will be a simple fix. Want to take a stab @sfc-gh-zblackwood?

I think we'd just need to update this line here - https://github.com/Snowflake-Labs/snowcli/blob/main/src/snowcli/snow_connector.py#L333

And have it use one of the Python `File` or `Path` class APIs to extract just the filename without any directory.

**Comment by sfc-gh-zblackwood** [comment]
@sfc-gh-jroes Happy to. I'll take a crack at it on Monday

**Comment by sfc-gh-jhollan** [comment]
Thanks much @sfc-gh-zblackwood - updated homebrew to include this fix
