### ISSUE TITLE
SNOW-982017: `snow object drop` should have more helpful error message

### ISSUE THREAD

**Issue by sfc-gh-zblackwood** [Snowflake-Labs/snowcli#579]
### SnowCLI version

SnowCLI Version: 2.0.0-alpha.1

### What happened

Ran `snow object drop`

> An unexpected exception occurred. Use --debug option to see the traceback.
> Exception message:
> 'NoneType' object has no attribute 'lower'

Instead should have some clear error saying "missing required arguments object_type and object_name"

Ran `snow object drop streamlit`

> An unexpected exception occurred. Use --debug option to see the traceback.
> Exception message:
> 002003 (02000): SQL compilation error:
> Streamlit 'STREAMLIT.SIS_APPS.NONE' does not exist or not authorized.

Instead should have some clear error saying "missing required argument object_name"

**Comment by sfc-gh-astus** [comment]
Added checking not only for drop command #583

**Comment by sfc-gh-astus** [comment]
Merged
