### ISSUE TITLE
SNOW-1007798: Bad Owner Warning - config.toml

### ISSUE THREAD

**Issue by sfc-gh-mchilds** [Snowflake-Labs/snowcli#650]
### SnowCLI version

SnowCLI Version: 2.0.0a3

### Python version

Python 3.8.18

### Platform

macOS-10.16-x86_64-i386-64bit

### What happened

When running snow object to load the yaml file up to the Snowflake stage I get a warning that the config.toml has a bad owner or bad permissions.  I tried changing the owner with chown or using chmod to change the permissions - but the error persists.

### Console output

```Shell
/Users/mchilds/opt/anaconda3/lib/python3.8/site-packages/snowflake/connector/config_manager.py:344: UserWarning: Bad owner or permissions on /Users/mchilds/Library/Application Support/snowflake/config.toml. To change owner, run `chown $USER /Users/mchilds/Library/Application Support/snowflake/config.toml`. To restrict permissions, run `chmod 0600 /Users/mchilds/Library/Application Support/snowflake/config.toml`.
  warn(f"Bad owner or permissions on {str(filep)}{chmod_message}")
```

### How to reproduce

snow object stage copy ./convert-api.yaml @specs --overwrite --connection CONTAINER_hol

**Comment by sfc-gh-mkeller** [comment]
Please post the permissions of your file. Our library checks whether the file is readable by other https://github.com/snowflakedb/snowflake-connector-python/blob/25f2547f11f17701f54ac6409cea9c764a0027b3/src/snowflake/connector/config_manager.py#L329

**Comment by sfc-gh-dkincaid** [comment]
Had this same issue today. It looks like when the config.toml file first got created it had broader permissions, screenshot below. I was able to resolve the warning message by running the recommended  `chmod` 0600 "/Users/[username]/Library/Application Support/snowflake/config.toml"`
![FIlePermissions](https://github.com/Snowflake-Labs/snowcli/assets/129796055/eda68ba3-9115-4f7c-a976-b0520b0f68d7)
