### ISSUE TITLE
SNOW-1038470: Support for network integrations in SPCS

### ISSUE THREAD

**Issue by sfc-gh-cconner** [Snowflake-Labs/snowcli#722]
### Description

Can we add support for network integrations to allow outgoing access for SPCS?

### Context

For example from docs:

https://docs.snowflake.com/en/developer-guide/snowpark-container-services/additional-considerations-services-jobs#configuring-network-capabilities

`
CREATE SERVICE eai_service
  IN COMPUTE POOL MYPOOL
  FROM SPECIFICATION
  $$
  spec:
    containers:
      - name: main
        image: /db/data_schema/tutorial_repository/my_echo_service_image:tutorial
        env:
          TEST_FILE_STAGE: source_stage/test_file
        args:
          - read_secret.py
    endpoints:
      - name: read
        port: 8080
  $$
  EXTERNAL_ACCESS_INTEGRATIONS = (GOOGLE_APIS_ACCESS_INTEGRATION);
`

**Comment by sfc-gh-davwang** [comment]
This PR (included in 2.0) adds an option for external access integrations to create service if that's what you're asking for: https://github.com/Snowflake-Labs/snowcli/pull/679

**Comment by sfc-gh-cconner** [comment]
That is, thanks!

**Comment by sfc-gh-astus** [comment]
@sfc-gh-cconner did you check it? Can we close issue?

**Comment by sfc-gh-cconner** [comment]
Yes, we should close this, thanks!
