### ISSUE TITLE
InterpolationSyntaxError

### ISSUE THREAD

**Issue by mbkupfer** [Snowflake-Labs/snowcli#77]
If someone's password has a `%` symbol then an `InterpolationSyntaxError` will be thrown

**Comment by sfc-gh-jhollan** [comment]
Thanks for reporting! Let me see if I can figure out where this is happening and help prevent. Curious if this also happens with the `snowsql` CLI if you know

**Comment by mbkupfer** [comment]
> Curious if this also happens with the snowsql CLI if you know

Not sure. I'm actually just using both of these for the first time to see what they are about.

**Comment by sfc-gh-jhollan** [comment]
Looks like a flag we can set when we parse this to get around. In the meantime, looks like adding `%%` in the config file will get around

**Comment by mbkupfer** [comment]
Yup, that seems to do the trick, but now running into a different error so can't 100% confirm. I can create a separate issue for that to keep things tidy.

**Comment by sfc-gh-jhollan** [comment]
Heads up - that pull request will change the behavior (I believe) so you may need to undo this workaround :)
