### ISSUE TITLE
'zip' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mbkupfer** [Snowflake-Labs/snowcli#78]
I'm getting this error when running `snow function package`

Here is the full output
```
Resolving any requirements from requirements.txt...
Comparing provided packages from Snowflake Anaconda...
No packages to manually resolve
Writing requirements.snowflake.txt file...
'zip' is not recognized as an internal or external command,
operable program or batch file.


Deployment package now ready: app.zip

```

So first off, the final message is misleading since app.zip was never created.

The reason for this issue though is in the `os.system(f'zip -r ....)` calls that fail on my windows system. This could be fixed by using the python standard lib package, zipfile.py.

**Comment by robmir1** [comment]
How did you resolve it?

**Comment by mbkupfer** [comment]
@robmir1 I did not. Considering this project is still super early and not critical for my development I'm holding off till it matures. That said if you really need it, I believe your options are 1) use wsl, 2) zip the files yourself or 3) create a fork that uses zipfile in the places that zip things up

**Comment by sfc-gh-jhollan** [comment]
zipfile is right answer here. Just haven’t gotten chance to add 😬. Let me
see if I can pull it off before meetings start this morning
